In [1]:
# Import required libraries and read test and train data set
import pandas as pd
import numpy as np

## Winter Dataset

In [2]:
winter_dataset = pd.read_csv("Generated Dataset/winter_dataset.csv")
winter_dataset = winter_dataset.drop(["Unnamed: 0"], axis = 1)
# log the GDP and Population
winter_dataset["PopulationSize"] = np.log(winter_dataset["PopulationSize"])
winter_dataset["GDPPerCapita"] = np.log(winter_dataset["GDPPerCapita"])
winter_dataset.head(10)

,CountryCode,Year,OlympicsSeason,TotalParticipants,GoldMedals,SilverMedals,BronzeMedals,TotalMedals,Win%,GDPPerCapita,...,PrevTotalParticipants,PrevGoldMedals,PrevSilverMedals,PrevBronzeMedals,PrevTotalMedals,PrevSummerTotalParticipants,PrevSummerGoldMedals,PrevSummerSilverMedals,PrevSummerBronzeMedals,PrevSummerTotalMedals
0,AUS,1924,8,1,1,0,0,1,100.00,8.254516,...,0,0,0,0,0,60,3,5,2,10
1,AUT,1924,8,4,3,1,0,4,100.00,8.254516,...,0,0,0,0,0,56,0,3,1,4
2,BEL,1924,8,32,0,0,5,5,15.62,8.254516,...,0,0,0,0,0,234,3,30,6,39
3,CAN,1924,8,17,9,0,0,9,52.94,8.254516,...,0,0,0,0,0,83,0,19,1,20
4,CZE,1924,8,31,0,0,0,0,0.00,8.254516,...,0,0,0,0,0,242,1,4,5,10
5,FIN,1924,8,33,4,8,3,15,45.45,8.254516,...,0,0,0,0,0,253,24,13,15,52
6,FRA,1924,8,68,0,0,10,10,14.71,8.254516,...,0,0,0,0,0,636,37,51,22,110
7,GBR,1924,8,50,16,4,11,31,62.00,8.254516,...,0,0,0,0,0,428,15,30,19,64
8,HUN,1924,8,6,0,0,0,0,0.00,8.254516,...,0,0,0,0,0,140,2,12,8,22
9,IND,1924,8,7,7,0,0,7,100.00,8.254516,...,0,0,0,0,0,24,0,0,0,0

In [3]:
# if the data is too few (less than 3), simply ignore that country
NOC_values_winter = dict(winter_dataset.groupby("CountryCode")["CountryCode"].value_counts())
ignore_value_winter = []
for key in NOC_values_winter:
    if NOC_values_winter[key] <= 3:
        ignore_value_winter.append(key[0])
len(ignore_value_winter)

30

In [4]:
# the data is not enough to split the validation set
# only extract the last year as the test dataset
test_winter = winter_dataset.groupby("CountryCode").apply(lambda x: x.iloc[len(x)-1:])
test_winter = pd.DataFrame(test_winter[(test_winter["TotalParticipants"] != 0) & (~(test_winter["CountryCode"].isin(ignore_value_winter)))]).reset_index(drop = True)
print(test_winter.shape)
NOC_neat_winter = list(test_winter["CountryCode"].unique())
NOC_neat_winter.sort()
train_winter = pd.DataFrame(winter_dataset[(winter_dataset["CountryCode"].isin(NOC_neat_winter)) & (winter_dataset["Year"] != 2016)]).reset_index(drop = True)
train_winter.head(20)

(78, 22)

,CountryCode,Year,OlympicsSeason,TotalParticipants,GoldMedals,SilverMedals,BronzeMedals,TotalMedals,Win%,GDPPerCapita,...,PrevTotalParticipants,PrevGoldMedals,PrevSilverMedals,PrevBronzeMedals,PrevTotalMedals,PrevSummerTotalParticipants,PrevSummerGoldMedals,PrevSummerSilverMedals,PrevSummerBronzeMedals,PrevSummerTotalMedals
0,AUS,1924,8,1,1,0,0,1,100.00,8.254516,...,0,0,0,0,0,60,3,5,2,10
1,AUT,1924,8,4,3,1,0,4,100.00,8.254516,...,0,0,0,0,0,56,0,3,1,4
2,BEL,1924,8,32,0,0,5,5,15.62,8.254516,...,0,0,0,0,0,234,3,30,6,39
3,CAN,1924,8,17,9,0,0,9,52.94,8.254516,...,0,0,0,0,0,83,0,19,1,20
4,CZE,1924,8,31,0,0,0,0,0.00,8.254516,...,0,0,0,0,0,242,1,4,5,10
5,FIN,1924,8,33,4,8,3,15,45.45,8.254516,...,0,0,0,0,0,253,24,13,15,52
6,FRA,1924,8,68,0,0,10,10,14.71,8.254516,...,0,0,0,0,0,636,37,51,22,110
7,GBR,1924,8,50,16,4,11,31,62.00,8.254516,...,0,0,0,0,0,428,15,30,19,64
8,HUN,1924,8,6,0,0,0,0,0.00,8.254516,...,0,0,0,0,0,140,2,12,8,22
9,IND,1924,8,7,7,0,0,7,100.00,8.254516,...,0,0,0,0,0,24,0,0,0,0
10,ITA,1924,8,24,0,0,0,0,0.00,8.254516,...,0,0,0,0,0,333,25,5,21,51
11,LAT,1924,8,7,0,0,0,0,0.00,8.254516,...,0,0,0,0,0,47,0,0,0,0
12,NEP,1924,8,1,1,0,0,1,100.00,8.254516,...,0,0,0,0,0,0,0,0,0,0
13,NOR,1924,8,36,4,7,6,17,47.22,8.254516,...,0,0,0,0,0,105,14,5,3,22
14,POL,1924,8,15,0,0,0,0,0.00,8.254516,...,0,0,0,0,0,100,0,4,1,5
15,SRB,1924,8,7,0,0,0,0,0.00,8.254516,...,0,0,0,0,0,116,2,0,0,2
16,SUI,1924,8,39,8,0,1,9,23.08,8.254516,...,0,0,0,0,0,262,14,25,21,60
17,SWE,1924,8,41,1,8,0,9,21.95,8.254516,...,0,0,0,0,0,256,7,22,43,72
18,USA,1924,8,41,1,10,1,12,29.27,8.254516,...,0,0,0,0,0,459,97,36,49,182
19,ARG,1928,9,10,0,0,0,0,0.00,8.254516,...,0,0,0,0,0,98,3,18,5,26

In [5]:
train_winter["CountryCode"].unique().shape

(78,)

In [6]:
predictors_winter = ["HostCity","GDPPerCapita","PopulationSize","TotalParticipants", "PrevTotalParticipants", "PrevGoldMedals", "PrevSilverMedals", "PrevBronzeMedals", "PrevTotalMedals",\
                      "PrevSummerTotalParticipants", "PrevSummerGoldMedals", "PrevSummerSilverMedals", "PrevSummerBronzeMedals", "PrevSummerTotalMedals"]
y_train_winter = pd.DataFrame(train_winter["TotalMedals"])
X_train_winter = pd.DataFrame(train_winter[predictors_winter])
y_test_winter = pd.DataFrame(test_winter["TotalMedals"])
X_test_winter = pd.DataFrame(test_winter[predictors_winter])

In [7]:
from tensorflow import keras

In [8]:
from sklearn.metrics import explained_variance_score
from sklearn.metrics import mean_squared_error

In [9]:
# add CallBacks: early-stopping: stop if there is no improvement on loss more than 100 epochs
earlystopping = keras.callbacks.EarlyStopping(monitor='loss', patience=100, mode='auto')

In [10]:
dense_layers = list(range(2, 11))

for dense_layer in dense_layers:
    NAME = "{}-layers-winter".format(dense_layer)
    # always save the best model
    checkpointfunc = keras.callbacks.ModelCheckpoint('Keras Models/{}.model'.format(NAME), monitor='loss', verbose=0,
                                                 save_best_only=True,
                                                 save_weights_only=False, mode='min', period=1)

    model = keras.Sequential()
    model.add(keras.layers.Dense(4, input_dim=14, activation='relu'))
    for i in range(dense_layer):
        model.add(keras.layers.Dense(4, activation='relu'))
    model.add(keras.layers.Dropout(0.3))
    model.add(keras.layers.Dense(1, activation='linear'))
    model.compile(loss='mse', optimizer='adam')
    model.fit(X_train_winter, y_train_winter, epochs=1000, verbose=0, callbacks=[checkpointfunc, earlystopping])
    
    y_test_pred = model.predict(np.array(X_test_winter))
    y_test_pred = list(y_test_pred)
    for i in range(len(y_test_pred)):
        if y_test_pred[i] < 0:
            y_test_pred[i] = 0
    y_test_pred = np.round(y_test_pred).astype("int")
    R2 = explained_variance_score(y_test_winter, y_test_pred)
    MSE = mean_squared_error(y_test_winter, y_test_pred)
    
    print("round", dense_layer, "finish", "R2: ", R2, "MSE: ", MSE)

round 2 finish R2:  0.0 MSE:  283.2435897435897
round 3 finish R2:  0.7932225993825197 MSE:  58.08974358974359
round 4 finish R2:  0.0 MSE:  283.2435897435897
round 5 finish R2:  0.802609613310106 MSE:  56.73076923076923
round 6 finish R2:  0.0 MSE:  283.2435897435897
round 7 finish R2:  0.8704334257385827 MSE:  36.8974358974359
round 8 finish R2:  0.0 MSE:  283.2435897435897
round 9 finish R2:  0.0 MSE:  283.2435897435897
round 10 finish R2:  0.8720524219609249 MSE:  36.62820512820513

#### 10 dense layers has the highest R2 and the lowest MSE, hence the best model;
### apply the model with 10 dense layers to predict the Winter Dataset

In [11]:
#to load a model
NAME = "{}-layers-winter".format(10)
model = keras.models.load_model('Keras Models/{}.model'.format(NAME))

In [12]:
y_test_pred_winter = model.predict(np.array(X_test_winter))
y_test_pred_winter = list(y_test_pred_winter)
for i in range(len(y_test_pred_winter)):
    if y_test_pred_winter[i] < 0:
        y_test_pred_winter[i] = 0
y_test_pred_winter = np.round(y_test_pred_winter).astype("int")

In [13]:
y_test_pred_df = pd.DataFrame(y_test_pred_winter)
y_test_df = pd.DataFrame(y_test_winter)
noc_df = pd.DataFrame(NOC_neat_winter)
result_winter = pd.concat([noc_df, y_test_df, y_test_pred_df], axis = 1)
result_winter.columns = ["Country", "True Value", "Predicted Value"]

In [14]:
result_winter.head(10)

  Country  True Value  Predicted Value
0     AND           0                1
1     ARG           0                1
2     ARM           0                1
3     AUS           3                6
4     AUT          27               30
5     AZE           0                1
6     BEL           0                1
7     BIH           0                1
8     BLR           6                5
9     BOL           0                1

In [15]:
# create the csv file
result_winter.to_csv("Results/Winter - Keras CNN Model.csv", index = 0)