In [1]:
# Import required libraries and read test and train data set
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt # we only need pyplot

#### Since population and GDP values are too large, they take too much weightage in regression; hence, take log on them

In [2]:
# summer dataset
summer_dataset = pd.read_csv("Generated Dataset/summer_dataset.csv")
summer_dataset = summer_dataset.drop(["Unnamed: 0"], axis = 1)
summer_dataset["PopulationSize"] = np.log(summer_dataset["PopulationSize"])
summer_dataset["GDPPerCapita"] = np.log(summer_dataset["GDPPerCapita"])
summer_dataset.head(10)

,CountryCode,Year,OlympicsSeason,TotalParticipants,GoldMedals,SilverMedals,BronzeMedals,TotalMedals,Win%,GDPPerCapita,...,PrevTotalParticipants,PrevGoldMedals,PrevSilverMedals,PrevBronzeMedals,PrevTotalMedals,PrevWinterTotalParticipants,PrevWinterGoldMedals,PrevWinterSilverMedals,PrevWinterBronzeMedals,PrevWinterTotalMedals
0,AUS,1896,1,5,2,0,1,3,60.00,6.826319,...,0,0,0,0,0,0,0,0,0,0
1,AUT,1896,1,8,2,1,2,5,62.50,6.826319,...,0,0,0,0,0,0,0,0,0,0
2,DEN,1896,1,15,1,2,3,6,40.00,6.826319,...,0,0,0,0,0,0,0,0,0,0
3,FRA,1896,1,26,5,4,2,11,42.31,6.826319,...,0,0,0,0,0,0,0,0,0,0
4,GBR,1896,1,25,3,3,3,9,36.00,6.826319,...,0,0,0,0,0,0,0,0,0,0
5,GER,1896,1,94,25,5,2,32,34.04,6.826319,...,0,0,0,0,0,0,0,0,0,0
6,GRE,1896,1,148,10,18,20,48,32.43,6.826319,...,0,0,0,0,0,0,0,0,0,0
7,HUN,1896,1,18,2,1,3,6,33.33,6.826319,...,0,0,0,0,0,0,0,0,0,0
8,ITA,1896,1,1,0,0,0,0,0.00,6.826319,...,0,0,0,0,0,0,0,0,0,0
9,SUI,1896,1,8,1,2,0,3,37.50,6.826319,...,0,0,0,0,0,0,0,0,0,0

In [3]:
# winter dataset
winter_dataset = pd.read_csv("Generated Dataset/winter_dataset.csv")
winter_dataset = winter_dataset.drop(["Unnamed: 0"], axis = 1)
winter_dataset["PopulationSize"] = np.log(winter_dataset["PopulationSize"])
winter_dataset["GDPPerCapita"] = np.log(winter_dataset["GDPPerCapita"])
winter_dataset.head(10)

,CountryCode,Year,OlympicsSeason,TotalParticipants,GoldMedals,SilverMedals,BronzeMedals,TotalMedals,Win%,GDPPerCapita,...,PrevTotalParticipants,PrevGoldMedals,PrevSilverMedals,PrevBronzeMedals,PrevTotalMedals,PrevSummerTotalParticipants,PrevSummerGoldMedals,PrevSummerSilverMedals,PrevSummerBronzeMedals,PrevSummerTotalMedals
0,AUS,1924,8,1,1,0,0,1,100.00,8.254516,...,0,0,0,0,0,60,3,5,2,10
1,AUT,1924,8,4,3,1,0,4,100.00,8.254516,...,0,0,0,0,0,56,0,3,1,4
2,BEL,1924,8,32,0,0,5,5,15.62,8.254516,...,0,0,0,0,0,234,3,30,6,39
3,CAN,1924,8,17,9,0,0,9,52.94,8.254516,...,0,0,0,0,0,83,0,19,1,20
4,CZE,1924,8,31,0,0,0,0,0.00,8.254516,...,0,0,0,0,0,242,1,4,5,10
5,FIN,1924,8,33,4,8,3,15,45.45,8.254516,...,0,0,0,0,0,253,24,13,15,52
6,FRA,1924,8,68,0,0,10,10,14.71,8.254516,...,0,0,0,0,0,636,37,51,22,110
7,GBR,1924,8,50,16,4,11,31,62.00,8.254516,...,0,0,0,0,0,428,15,30,19,64
8,HUN,1924,8,6,0,0,0,0,0.00,8.254516,...,0,0,0,0,0,140,2,12,8,22
9,IND,1924,8,7,7,0,0,7,100.00,8.254516,...,0,0,0,0,0,24,0,0,0,0

In [4]:
summer_dataset_2020 = pd.read_csv("Generated Dataset/2020 Olympics.csv")
# log the GDP and Population
summer_dataset_2020["PopulationSize"] = np.log(summer_dataset_2020["PopulationSize"])
summer_dataset_2020["GDPPerCapita"] = np.log(summer_dataset_2020["GDPPerCapita"])
summer_dataset_2020.head(10)

,CountryCode,Year,OlympicsSeason,TotalParticipants,GoldMedals,SilverMedals,BronzeMedals,TotalMedals,Win%,GDPPerCapita,...,PrevTotalParticipants,PrevGoldMedals,PrevSilverMedals,PrevBronzeMedals,PrevTotalMedals,PrevWinterTotalParticipants,PrevWinterGoldMedals,PrevWinterSilverMedals,PrevWinterBronzeMedals,PrevWinterTotalMedals
0,AFG,2016,NaN,3,NaN,NaN,NaN,NaN,NaN,6.091294,...,3,0,0,0,0,0,0,0,0,0
1,ALB,2016,NaN,6,NaN,NaN,NaN,NaN,NaN,8.350814,...,6,0,0,0,0,2,0,0,0,0
2,ALG,2016,NaN,74,NaN,NaN,NaN,NaN,NaN,8.462153,...,74,0,2,0,2,0,0,0,0,0
3,AND,2016,NaN,4,NaN,NaN,NaN,NaN,NaN,10.754391,...,4,0,0,0,0,12,0,0,0,0
4,ANG,2016,NaN,26,NaN,NaN,NaN,NaN,NaN,8.380535,...,26,0,0,0,0,0,0,0,0,0
5,ANT,2016,NaN,9,NaN,NaN,NaN,NaN,NaN,9.720109,...,9,0,0,0,0,0,0,0,0,0
6,ARG,2016,NaN,232,NaN,NaN,NaN,NaN,NaN,9.059287,...,232,21,1,0,22,20,0,0,0,0
7,ARM,2016,NaN,34,NaN,NaN,NaN,NaN,NaN,8.521416,...,34,1,3,0,4,6,0,0,0,0
8,ARU,2016,NaN,7,NaN,NaN,NaN,NaN,NaN,10.326632,...,7,0,0,0,0,0,0,0,0,0
9,ASA,2016,NaN,4,NaN,NaN,NaN,NaN,NaN,9.581031,...,4,0,0,0,0,0,0,0,0,0

In [5]:
# if the data is too few (less than 3), simply ignore that country
NOC_values = dict(summer_dataset.groupby("CountryCode")["CountryCode"].value_counts())
ignore_value = []
for key in NOC_values:
    if NOC_values[key] <= 3:
        ignore_value.append(key[0])
ignore_value

['AHO', 'ANZ', 'CRT', 'MHL', 'MNE', 'NFL', 'TPE', 'TUV', 'UNK']

In [6]:
summer_dataset_2020 = pd.DataFrame(summer_dataset_2020[(~(summer_dataset_2020["CountryCode"].isin(ignore_value)))]).reset_index(drop = True)
NOC_2020 = pd.DataFrame(list(summer_dataset_2020["CountryCode"]))
NOC_2020.shape

(194, 1)

In [7]:
predictors = ["HostCity","GDPPerCapita","PopulationSize","TotalParticipants", "PrevTotalParticipants", "PrevGoldMedals", "PrevSilverMedals", "PrevBronzeMedals", "PrevTotalMedals",\
                      "PrevWinterTotalParticipants", "PrevWinterGoldMedals", "PrevWinterSilverMedals", "PrevWinterBronzeMedals", "PrevWinterTotalMedals"]
temp = pd.DataFrame(summer_dataset_2020[predictors])
temp.isnull().any()

HostCity                       False
GDPPerCapita                   False
PopulationSize                 False
TotalParticipants              False
PrevTotalParticipants          False
PrevGoldMedals                 False
PrevSilverMedals               False
PrevBronzeMedals               False
PrevTotalMedals                False
PrevWinterTotalParticipants    False
PrevWinterGoldMedals           False
PrevWinterSilverMedals         False
PrevWinterBronzeMedals         False
PrevWinterTotalMedals          False
dtype: bool

In [8]:
# Import the model we are using
from sklearn.ensemble import RandomForestRegressor

# function to make predictions of a specific country
def random_forest_prediction(NOC, season): # the input should be 2 strings
    if season == "Summer":
        dataset = summer_dataset
        predictors = ["HostCity","GDPPerCapita","PopulationSize","TotalParticipants", "PrevTotalParticipants", "PrevGoldMedals", "PrevSilverMedals", "PrevBronzeMedals", "PrevTotalMedals",\
                      "PrevWinterTotalParticipants", "PrevWinterGoldMedals", "PrevWinterSilverMedals", "PrevWinterBronzeMedals", "PrevWinterTotalMedals"]
    elif season == "Winter":
        dataset = winter_dataset
        predictors = ["HostCity","GDPPerCapita","PopulationSize","TotalParticipants", "PrevTotalParticipants", "PrevGoldMedals", "PrevSilverMedals", "PrevBronzeMedals", "PrevTotalMedals",\
                      "PrevSummerTotalParticipants", "PrevSummerGoldMedals", "PrevSummerSilverMedals", "PrevSummerBronzeMedals", "PrevSummerTotalMedals"]
        
    Country = pd.DataFrame(dataset[(dataset["CountryCode"] == NOC) & (dataset["TotalParticipants"] != 0)])
    Country = Country.reset_index(drop = True)
    
    # if the provided data that country is too few (less than 3), it is not enough to make prediction; just drop it
    if (len(Country) <= 3): 
        return ["No Value", "No Value"]
    
    NOC_train = pd.DataFrame(Country[:len(dataset)-1])

    NOC_test = pd.DataFrame(Country[-1:])


    y_train = np.array(NOC_train["TotalMedals"])
    X_train = np.array(NOC_train[predictors])

    y_test = np.array(NOC_test["TotalMedals"])
    X_test = np.array(NOC_test[predictors])
    

    # Instantiate model with 1000 decision trees
    rf = RandomForestRegressor(n_estimators = 1000, random_state = 42)
    # Train the model on training data
    rf.fit(X_train, y_train)
    
    # Use the forest's predict method on the test data
    y_train_pred = rf.predict(X_train)
    # Use the forest's predict method on the test data
    y_test_pred = rf.predict(X_test)
    
    return_true_list = list(y_test)
    return_prediction_list = list(y_test_pred)
    for i in range(len(y_test_pred)):
        return_prediction_list[i] = int(round(return_prediction_list[i]))
        #print(return_prediction_list[i])
        
    # to predict 2020
    if season == "Summer":
        if NOC in summer_dataset_2020["CountryCode"].tolist():
            X_test_2020 = summer_dataset_2020[summer_dataset_2020["CountryCode"] == NOC][predictors]
            y_test_pred_2020 = rf.predict(X_test_2020)
            temp = list(y_test_pred_2020)[0]
            if temp < 0:
                temp = 0
            result_2020 = [int(round(temp))]
        else:
            result_2020 = ["n"]

        return [list(NOC_test["Year"]), return_true_list, return_prediction_list, result_2020]
    
    elif season == "Winter":
        return [list(NOC_test["Year"]), return_true_list, return_prediction_list]

In [9]:
# function to apply prediction to each countries: feed the data of every countries into the model one-by-one
def prediction_implementation(season): # the input should be a string
    if season == "Summer":
        dataset = summer_dataset
    elif season == "Winter":
        dataset = winter_dataset
    
    # generate the list of predicted value
    NOC_neat = list(dataset["CountryCode"].unique())
    NOC_neat.sort()
    print(NOC_neat)
    year = []
    true_value = []
    prediction = []
    remove_list = []
    result_2020 = []
    for i in NOC_neat:
        # call the prediction function
        NOC = random_forest_prediction(i, season)
        if(type(NOC[0]) != str):
            year.extend(NOC[0])
            true_value.extend(NOC[1])
            prediction.extend(NOC[2])
            if season == "Summer":
                if (type(NOC[3][0]) != str):
                    result_2020.extend(NOC[3])    
        else:
            print(i) # print out the countries that is dropped
            remove_list.append(i)
    
    # generate the dataframe of predicted value and true value
    NOC_final = NOC_neat.copy()
    for i in range(len(remove_list)):
        NOC_final.remove(remove_list[i])

    NOC_df = pd.DataFrame(NOC_final)
    year_df = pd.DataFrame(year)
    True_df = pd.DataFrame(true_value)
    Prediction_df = pd.DataFrame(prediction)
    result_2020_df = pd.DataFrame(result_2020)
    
    Result = pd.concat([NOC_df, year_df, True_df, Prediction_df], axis = 1)
    Result.columns = ["Country", "Year", "True Value", "Predicted Value"]
    
    if season == "Summer":
        result_2020_df = pd.concat([NOC_2020, result_2020_df], axis = 1)
        result_2020_df.columns = ["Country", "Predicted Medals"]
        return (Result, true_value, prediction, result_2020_df)
    elif season == "Winter":
        return (Result, true_value, prediction)

In [10]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import explained_variance_score

#### Summer Dataset

In [11]:
result_summer = prediction_implementation("Summer")
Result_summer = result_summer[0]
true_value_summer = result_summer[1]
prediction_summer = result_summer[2]
    
print("Test Explained Variance (R^2) of Summer Olympics \t:", explained_variance_score(true_value_summer, prediction_summer))
print("Test Mean Squared Error (MSE) of Summer Olympics \t:", mean_squared_error(true_value_summer, prediction_summer))
print()

['AFG', 'AHO', 'ALB', 'ALG', 'AND', 'ANG', 'ANT', 'ANZ', 'ARG', 'ARM', 'ARU', 'ASA', 'AUS', 'AUT', 'AZE', 'BAN', 'BAR', 'BDI', 'BEL', 'BEN', 'BHU', 'BIH', 'BIZ', 'BLR', 'BOH', 'BOL', 'BOT', 'BRA', 'BRN', 'BRU', 'BUL', 'BUR', 'CAF', 'CAM', 'CAN', 'CAY', 'CGO', 'CHA', 'CHI', 'CHN', 'CIV', 'CMR', 'COD', 'COL', 'COM', 'CPV', 'CRC', 'CRO', 'CRT', 'CUB', 'CYP', 'CZE', 'DEN', 'DJI', 'DMA', 'DOM', 'ECU', 'EGY', 'ESA', 'ESP', 'EST', 'ETH', 'FIJ', 'FIN', 'FRA', 'FSM', 'GAB', 'GAM', 'GBR', 'GBS', 'GEO', 'GEQ', 'GER', 'GHA', 'GRE', 'GRN', 'GUA', 'GUI', 'GUM', 'GUY', 'HAI', 'HKG', 'HON', 'HUN', 'INA', 'IND', 'IRI', 'IRL', 'IRQ', 'ISL', 'ISR', 'ISV', 'ITA', 'IVB', 'JAM', 'JOR', 'JPN', 'KAZ', 'KEN', 'KGZ', 'KIR', 'KOR', 'KSA', 'KUW', 'LAO', 'LAT', 'LBA', 'LBR', 'LCA', 'LES', 'LIB', 'LIE', 'LTU', 'LUX', 'MAD', 'MAR', 'MAS', 'MAW', 'MDA', 'MDV', 'MEX', 'MGL', 'MHL', 'MKD', 'MLI', 'MLT', 'MNE', 'MON', 'MOZ', 'MRI', 'MTN', 'MYA', 'NAM', 'NCA', 'NED', 'NEP', 'NFL', 'NGR', 'NIG', 'NOR', 'NRU', 'NZL', 'OMA', 'PAK', 'PAN', 'PAR', 'PER', 'PHI', 'PLE', 'PLW', 'PNG', 'POL', 'POR', 'PRK', 'PUR', 'QAT', 'ROU', 'RSA', 'RUS', 'RWA', 'SAM', 'SEN', 'SEY', 'SKN', 'SLE', 'SLO', 'SMR', 'SOL', 'SOM', 'SRB', 'SRI', 'STP', 'SUD', 'SUI', 'SUR', 'SVK', 'SWE', 'SWZ', 'SYR', 'TAN', 'TGA', 'THA', 'TJK', 'TKM', 'TLS', 'TOG', 'TPE', 'TRI', 'TUN', 'TUR', 'TUV', 'UAE', 'UGA', 'UKR', 'UNK', 'URU', 'USA', 'UZB', 'VAN', 'VEN', 'VIE', 'VIN', 'YEM', 'ZAM', 'ZIM']
AHO
ANZ
CRT
MHL
MNE
NFL
TPE
TUV
UNK
Test Explained Variance (R^2) of Summer Olympics 	: 0.9838242903831448
Test Mean Squared Error (MSE) of Summer Olympics 	: 14.505102040816327

#### Winter Dataset

In [12]:
result_winter = prediction_implementation("Winter")
Result_winter = result_winter[0]
true_value_winter = result_winter[1]
prediction_winter = result_winter[2]

print("Test Explained Variance (R^2) of Winter Olympics \t:", explained_variance_score(true_value_winter, prediction_winter))
print("Test Mean Squared Error (MSE) of Winter Olympics \t:", mean_squared_error(true_value_winter, prediction_winter))
print()

['ALB', 'ALG', 'AND', 'ARG', 'ARM', 'ASA', 'AUS', 'AUT', 'AZE', 'BEL', 'BIH', 'BLR', 'BOL', 'BRA', 'BUL', 'CAN', 'CAY', 'CHI', 'CHN', 'CMR', 'COL', 'CRC', 'CRO', 'CYP', 'CZE', 'DEN', 'DMA', 'EGY', 'ESP', 'EST', 'ETH', 'FIJ', 'FIN', 'FRA', 'GBR', 'GEO', 'GER', 'GHA', 'GRE', 'GUA', 'GUM', 'HKG', 'HON', 'HUN', 'IND', 'IRI', 'IRL', 'ISL', 'ISR', 'ISV', 'ITA', 'IVB', 'JAM', 'JPN', 'KAZ', 'KEN', 'KGZ', 'KOR', 'LAT', 'LIB', 'LIE', 'LTU', 'LUX', 'MAD', 'MAR', 'MDA', 'MEX', 'MGL', 'MKD', 'MLT', 'MNE', 'MON', 'NED', 'NEP', 'NOR', 'NZL', 'PAK', 'PAR', 'PER', 'PHI', 'POL', 'POR', 'PRK', 'PUR', 'ROU', 'RSA', 'RUS', 'SEN', 'SLO', 'SMR', 'SRB', 'SUI', 'SVK', 'SWE', 'SWZ', 'TGA', 'THA', 'TJK', 'TLS', 'TOG', 'TRI', 'TUR', 'UKR', 'URU', 'USA', 'UZB', 'VEN', 'ZIM']
ALB
ALG
ASA
CAY
CMR
COL
DMA
EGY
ETH
FIJ
GHA
GUA
GUM
HON
IVB
KEN
MAD
MLT
MNE
PAK
PAR
PER
SWZ
TGA
THA
TLS
TOG
TRI
URU
ZIM
Test Explained Variance (R^2) of Winter Olympics 	: 0.9809470571242572
Test Mean Squared Error (MSE) of Winter Olympics 	: 5.6923076923076925

In [13]:
Olympic_2020 = result_summer[3]

In [14]:
print(Olympic_2020.shape)
Olympic_2020.head()

(194, 2)

  Country  Predicted Medals
0     AFG                 1
1     ALB                 0
2     ALG                 1
3     AND                 0
4     ANG                 0

In [15]:
# create the csv file
Result_summer.to_csv("Results/Summer - Random Forest Model.csv", index = 0)

In [16]:
Result_winter.to_csv("Results/Winter - Random Forest Model.csv", index = 0)

In [17]:
Olympic_2020.to_csv("Results/Summer 2020 - Random Forest Model.csv", index = 0)